# The public documentation URL, used for sitemap.xml
url: "https://docs.telerik.com/aspnet-mvc"

all_pages_domain: "https://docs.telerik.com"

capital_casing_redirects: true

# Exclude files which should not be in the output
exclude: [README.md, Gemfile, Gemfile.lock,api_sort.rb, Dockerfile, bs-config.js, build-docs.sh, copy_content.sh, copy_local.sh, docs-watcher/*, exclude_files.txt, install-npm.sh, start-docs.sh, watch.sh]
exclude_navigation: [asp-net-mvc-3.html,asp-net-mvc-4.html,api/Kendo.Mvc/*,api/Kendo.Mvc.UI/*,api/Kendo.Mvc.UI.Fluent/*]
navigation:
## List your directory names and order here, like this:

     "api":
        title: "API Reference"
        position: 0
     "getting-started":
        title: "Getting Started"
        position: 2
     "helpers":
        title: "HTML Helpers"
        position: 3
     "helpers/barcodes":
        title: "Barcodes"
     "helpers/charts":
        title: "Charts"
     "helpers/charts/stockchart":
        title: "StockChart"
        position: 4
     "helpers/charts/treemap":
        title: "TreeMap"
        position: 5
     "helpers/conversational-ui":
        title: "Conversational UI"
     "helpers/data-management":
        title: "Data Management"
     "helpers/data-management/pivotgrid":
        title: "PivotGrid"
     "helpers/diagrams-and-maps":
        title: "Diagrams and Maps"
     "helpers/editors":
        title: "Editors"
     "helpers/editors/autocomplete/binding":
        title: "Data Binding"
        position: 2
     "helpers/editors/combobox/binding":
        title: "Data Binding"
        position: 2
     "helpers/editors/dropdownlist/binding":
        title: "Data Binding"
        position: 2
     "helpers/editors/multicolumncombobox/binding":
        title: "Data Binding"
        position: 2
     "helpers/editors/multiselect/binding":
        title: "Data Binding"
        position: 2
     "helpers/gauges":
        title: "Gauges"
     "helpers/hybrid":
        title: "Hybrid"
     "helpers/interactivity":
        title: "Interactivity and UX"
     "helpers/layout":
        title: "Layout"
     "helpers/media":
        title: "Media"
     "helpers/navigation":
        title: "Navigation"
     "helpers/navigation/radiobutton":
        title: "RadioButton"
     "helpers/navigation/panelbar":
        title: "PanelBar"
     "helpers/pdf":
        title: "PDF"
     "helpers/scheduling":
        title: "Scheduling"
     "helpers/scheduling/multiviewcalendar":
        title: "MultiViewCalendar"
     "vs-integration":
        title: "Visual Studio Integration"
        position: 4
     "migration":
        title: "Migration"
        position: 5
     "styles-and-layout":
        title: "Styles and Appearance"
        position: 6
     "accessibility":
        title: "Accessibility"
        position: 7
     "how-to":
        title: "How To"
        position: 8
     "tutorials":
        title: "Tutorials"
        position: 9
     "troubleshoot":
        title: "Troubleshooting"
        position: 10

## List helpers directory names and order here, like this:
     "*autocomplete":
        title: "AutoComplete"
     "*barcode":
        title: "Barcode"
     "*button":
        title: "Button"
     "*buttongroup":
        title: "ButtonGroup"
     "*calendar":
        title: "Calendar"
     "*chart":
        title: "Chart"
     "*chat":
        title: "Chat"
        isNew: true
     "*colorpalette":
        title: "ColorPalette"
     "*flatcolorpicker":
        title: "FlatColorPicker"
     "*colorpicker":
        title: "ColorPicker"
     "*multicolumncombobox":
        title: "MultiColumnComboBox"
     "*combobox":
        title: "ComboBox"
     "*dateinput":
        title: "DateInput"
     "*datepicker":
        title: "DatePicker"
     "*daterangepicker":
        title: "DateRangePicker"
     "*datetimepicker":
        title: "DateTimePicker"
     "*diagram":
        title: "Diagram"
     "*dialog":
        title: "Dialog"
     "*dropdownlist":
        title: "DropDownList"
     "*dropdowntree":
        isNew: true
        title: "DropDownTree"
     "*drawer":
        isNew: true
        title: "Drawer"
     "*editor":
        title: "Editor"
     "*gantt":
        title: "Gantt"
     "*grid":
        title: "Grid"
     "helpers/data-management/grid/binding":
        title: "Data Binding"
        position: 4
     "helpers/data-management/grid/editing":
        title: "Editing"
        position: 5
     "helpers/data-management/grid/templating":
        title: "Templates"
        position: 6
     "helpers/data-management/grid/how-to":
        title: "How To"
        position: 30
     "helpers/editors/upload/how-to":
        title: "How To"
        position: 30
     "helpers/data-management/grid/troubleshoot":
        title: "Troubeshooting"
        position: 40
     "*appearance":
        title: "Appearance"
     "*binding":
        title: "Binding"
     "*troubleshoot":
        title: "Troubleshooting"
     "*editing":
        title: "Editing"
     "*export":
        title: "Export"
     "*filtering":
        title: "Filtering"
     "*integration":
        title: "Integration"
     "*selection":
        title: "Selection"
     "*state":
        title: "State Management"
     "*how-to":
        title: "How To"
     "*hybrid":
        title: "Hybrid"
     "*mobileactionsheet":
        title: "ActionSheet"
     "*mobileapplication":
        title: "Application"
     "*mobilebutton":
        title: "Button"
     "*mobilebuttongroup":
        title: "ButtonGroup"
     "*mobiledrawer":
        title: "Drawer"
     "*mobilelayout":
        title: "Layout"
     "*mobilelistview":
        title: "ListView"
     "*mobilemodalview":
        title: "ModalView"
     "*mobilenavbar":
        title: "NavBar"
     "*mobilepopover":
        title: "PopOver"
     "*mobilescrollview":
        title: "ScrollView"
     "*mobilesplitview":
        title: "SplitView"
     "*mobileswitch":
        title: "Switch"
     "*mobiletabstrip":
        title: "TabStrip"
     "*mobileview":
        title: "View"
     "*lineargauge":
        title: "LinearGauge"
     "*listview":
        title: "ListView"
     "*listbox":
        title: "ListBox"
     "*map":
        title: "Map"
     "*maskedtextbox":
        title: "MaskedTextBox"
     "*mediaplayer":
        title: "MediaPlayer"
     "*menu":
        title: "Menu"
     "*multiselect":
        title: "MultiSelect"
     "*multiviewcalendar":
        title: "MultiViewCalendar"
     "*notification":
        title: "Notification"
     "*numerictextbox":
        title: "NumericTextBox"
     "*rating":
        title: "Rating"
     "*panelbar":
        title: "PanelBar"
     "*pdfviewer":
        title: "PDFViewer"
     "*pivotgrid":
        title: "PivotGrid"
     "*progressbar":
        title: "ProgressBar"
     "*qrcode":
        title: "QRCode"
     "*arcgauge":
        title: "ArcGauge"
     "*radialgauge":
        title: "RadialGauge"
     "*radiobutton":
        title: "RadioButton"
     "*scheduler":
        title: "Scheduler"
     "*scrollview":
        title: "ScrollView"
     "*slider":
        title: "Slider"
     "*sortable":
        title: "Sortable"
     "*splitter":
        title: "Splitter"
     "*spreadsheet":
        title: "SpreadSheet"
     "*stockchart":
        title: "StockChart"
     "*switch":
        title: "Switch"
     "*tabstrip":
        title: "TabStrip"
     "*timepicker":
        title: "TimePicker"
     "*toolbar":
        title: "ToolBar"
     "*tooltip":
        title: "Tooltip"
     "*treelist":
        title: "TreeList"
     "*treemap":
        title: "TreeMap"
     "*treeview":
        title: "TreeView"
     "*upload":
        title: "Upload"
     "*window":
        title: "Window"

## List migration directory names and order here, like this:
     "migration/widgets":
        title: "Widgets"
        position: 2

## List tutorials directory names and order here, like this:
     "tutorials/quickstart":
        title: "Quick Start"
        position: 1
     "tutorials/tutorial-kendo-music-store":
        title: "Tutorial Kendo Music Store"
        position: 2
     "tutorials/tutorial-kendo-music-store/music-store-dashboard":
        title: "Music Store Dashboard"
        position: 2
     "tutorials/tutorial-kendo-music-store/music-store-web":
        title: "Music Store Web"
        position: 3
     "tutorials/tutorial-saleshub":
        title: "Tutorial Sales Hub"
        position: 3
     "tutorials/tutorial-saleshub/home-page":
        title: "Home Page"
        position: 2
     "tutorials/tutorial-saleshub/order-page":
        title: "Order Page"
        position: 3

## The application virtual path
baseurl: /aspnet-mvc

## The Kendo UI version used
cdnVersion: "2019.1.115"

## The MVC Core version used
mvcCoreVersion: "2019.1.115"

ff-sheet-id: 17DDhsKyPUgO6GlvL8WEfCCN6tikyInp4qpRGCvvs794

## Product
product: "Telerik UI for ASP.NET MVC"
platform: aspnet-mvc

## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "documentation"
        category: "default"
        product: "aspnet-mvc"
        editable: true
-
    scope:
        path: "aspnet-mvc"
    values:
        product: "aspnet-mvc"

    scope:
        path: "api"
    values:
        editable: false
        res_type: api
        kind: api

type_links:
    "kendo.Class": "/api/javascript/class"
    "kendo.data.DataSource": "/api/javascript/data/datasource"
    "Array": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array"
    "Blob": "https://developer.mozilla.org/en/docs/Web/API/Blob"
    "File": "https://developer.mozilla.org/en-US/docs/Web/API/File"
    "Boolean": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean"
    "Function": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function"
    "jQuery": "http://api.jquery.com/Types/#jQuery"
    "Promise": "http://api.jquery.com/Types/#Promise"
    "Object": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object"
    "Number": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number"
    "String": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String"

# Aliases available in the markdown template. The below will expand {{site.foo}} to Bar in the output
# "foo": "Bar"

# The google services configuration
google_tag_manager: GTM-6X92
gcs_engine: '001595215763381649090:rdwxfmavt8o'
gcs_api_key: 'AIzaSyDnvT29LoZiLUcywskEgTTum7j5pkx6s8I'

has_web_api_index: true
skip_tabbed_code: true
code_lang: true
api_columns_count: 2
edit_repo_url: https://github.com/telerik/kendo-ui-core/edit/master/docs-aspnet-mvc

download: http://www.telerik.com/download/aspnet-mvc

footer_social:
    facebook: https://www.facebook.com/Telerik/
    youtube: https://www.youtube.com/user/TelerikInc
    linkedin: https://www.linkedin.com/showcase/telerik/
    twitter: https://twitter.com/Telerik/


# Assets pipeline configuration
assets:
    cachebust: soft
    js_compressor: uglifier
    gzip: false

## Do not edit below this line
safe: false
markdown: MarkdownProcessor
